INSERT INTO movie_recommendation.movies (title, release_year, genre, description, director, duration) VALUES
('Inception', 2010, 'Sci-Fi', 'A skilled thief leads a team into the dreams of others.', 'Christopher Nolan', 148),
('The Shawshank Redemption', 1994, 'Drama', 'Two imprisoned men bond over years, finding solace and eventual redemption.', 'Frank Darabont', 142),
('The Godfather', 1972, 'Crime', 'The aging patriarch of an organized crime dynasty transfers control to his son.', 'Francis Ford Coppola', 175),
('The Dark Knight', 2008, 'Action', 'Batman battles the Joker, who unleashes chaos in Gotham City.', 'Christopher Nolan', 152),
('Pulp Fiction', 1994, 'Crime', 'The lives of two mob hitmen, a boxer, and a gangster intertwine in L.A.', 'Quentin Tarantino', 154),
('Forrest Gump', 1994, 'Drama', 'The presidencies of Kennedy and Johnson, events of Vietnam, and more unfold through the life of Forrest.', 'Robert Zemeckis', 142),
('The Matrix', 1999, 'Sci-Fi', 'A hacker discovers the world is a simulated reality and joins a rebellion.', 'Lana Wachowski, Lilly Wachowski', 136),
('Fight Club', 1999, 'Drama', 'An insomniac office worker forms an underground fight club with a soap salesman.', 'David Fincher', 139),
('Titanic', 1997, 'Romance', 'A young aristocrat falls in love with a kind but poor artist aboard the Titanic.', 'James Cameron', 195),
('Gladiator', 2000, 'Action', 'A betrayed Roman general seeks revenge against the corrupt emperor.', 'Ridley Scott', 155),
('The Lord of the Rings: The Fellowship of the Ring', 2001, 'Fantasy', 'A meek Hobbit and his companions set out on a journey to destroy a powerful ring.', 'Peter Jackson', 178),
('Star Wars: Episode IV - A New Hope', 1977, 'Sci-Fi', 'Luke Skywalker joins forces with a Jedi Knight to save the galaxy.', 'George Lucas', 121),
('The Lion King', 1994, 'Animation', 'A young lion prince flees his kingdom after the murder of his father.', 'Roger Allers, Rob Minkoff', 88),
('Back to the Future', 1985, 'Adventure', 'A teenager is sent back in time to 1955 and must ensure his parents fall in love.', 'Robert Zemeckis', 116),
('Jurassic Park', 1993, 'Adventure', 'A pragmatic paleontologist visits an amusement park with living dinosaurs.', 'Steven Spielberg', 127),
('The Avengers', 2012, 'Action', 'Earths mightiest heroes must come together to stop Loki and his army.', 'Joss Whedon', 143),
('Braveheart', 1995, 'History', 'Scottish warrior William Wallace leads his countrymen in a rebellion.', 'Mel Gibson', 178),
('The Social Network', 2010, 'Drama', 'The founding of Facebook, and the lawsuits that followed.', 'David Fincher', 120),
('Avengers: Endgame', 2019, 'Action', 'The Avengers assemble once more to undo the damage caused by Thanos.', 'Anthony Russo, Joe Russo', 181),
('The Silence of the Lambs', 1991, 'Thriller', 'A young FBI cadet must seek the help of an incarcerated cannibal killer.', 'Jonathan Demme', 118),
('Schindlers List', 1993, 'History', 'A German businessman saves the lives of more than a thousand Jewish refugees.', 'Steven Spielberg', 195),
('The Green Mile', 1999, 'Crime', 'The lives of guards on Death Row are affected by one of their charges.', 'Frank Darabont', 189),
('Interstellar', 2014, 'Sci-Fi', 'A team of explorers travel through a wormhole in space.', 'Christopher Nolan', 169),
('Saving Private Ryan', 1998, 'War', 'A group of U.S. soldiers go behind enemy lines to retrieve a paratrooper.', 'Steven Spielberg', 169),
('The Prestige', 2006, 'Mystery', 'Two stage magicians engage in a battle to create the ultimate illusion.', 'Christopher Nolan', 130),
('The Departed', 2006, 'Crime', 'An undercover cop and a mole in the police attempt to identify each other.', 'Martin Scorsese', 151),
('Whiplash', 2014, 'Drama', 'A promising young drummer enrolls at a cut-throat music conservatory.', 'Damien Chazelle', 106),
('Django Unchained', 2012, 'Western', 'With the help of a German bounty-hunter, a freed slave sets out to rescue his wife.', 'Quentin Tarantino', 165),
('The Wolf of Wall Street', 2013, 'Biography', 'The true story of Jordan Belfort, from a wealthy stockbroker to his downfall.', 'Martin Scorsese', 180),
('The Big Lebowski', 1998, 'Comedy', 'The Dude abides as he navigates life in L.A. after a mistaken identity case.', 'Joel Coen, Ethan Coen', 117),
('Spider-Man: Into the Spider-Verse', 2018, 'Animation', 'Teen Miles Morales becomes Spider-Man of his reality.', 'Bob Persichetti, Peter Ramsey, Rodney Rothman', 117),
('Toy Story', 1995, 'Animation', 'A cowboy doll is profoundly threatened when a new spaceman figure supplants him.', 'John Lasseter', 81),
('The Terminator', 1984, 'Action', 'A cyborg assassin is sent back in time to kill the mother of a future resistance leader.', 'James Cameron', 107),
('Alien', 1979, 'Sci-Fi', 'The crew of a spaceship encounters a deadly alien organism.', 'Ridley Scott', 117),
('Goodfellas', 1990, 'Crime', 'The rise and fall of a mob associate in the Italian-American crime syndicate.', 'Martin Scorsese', 146),
('Casablanca', 1942, 'Romance', 'A cynical expatriate finds a reason to fight the Nazis during WWII.', 'Michael Curtiz', 102),
('The Sound of Music', 1965, 'Musical', 'A woman leaves an Austrian convent to become a governess for a widower.', 'Robert Wise', 172),
('2001: A Space Odyssey', 1968, 'Sci-Fi', 'Humanity encounters a mysterious monolith that seems to affect human evolution.', 'Stanley Kubrick', 149),
('E.T. the Extra-Terrestrial', 1982, 'Sci-Fi', 'A troubled child summons the courage to help a friendly alien escape Earth.', 'Steven Spielberg', 115),
('The Grand Budapest Hotel', 2014, 'Comedy', 'A writer encounters the owner of a high-class hotel who recounts his adventures.', 'Wes Anderson', 99),
('Rocky', 1976, 'Drama', 'A small-time boxer gets a chance to fight the heavyweight champion.', 'John G. Avildsen', 120),
('La La Land', 2016, 'Romance', 'A jazz musician and an aspiring actress fall in love while pursuing their dreams.', 'Damien Chazelle', 128),
('Slumdog Millionaire', 2008, 'Drama', 'A Mumbai teen reflects on his life after being accused of cheating on a game show.', 'Danny Boyle', 120),
('The Intouchables', 2011, 'Biography', 'An aristocrat hires a young man from the projects to be his caregiver.', 'Olivier Nakache, Éric Toledano', 112),
('A Beautiful Mind', 2001, 'Biography', 'A brilliant mathematician struggles with schizophrenia.', 'Ron Howard', 135),
('Coco', 2017, 'Animation', 'A boy who dreams of becoming a musician embarks on a journey to the Land of the Dead.', 'Lee Unkrich, Adrian Molina', 105),
('The Incredibles', 2004, 'Animation', 'A family of undercover superheroes attempt to live a quiet suburban life.', 'Brad Bird', 115),
('The Shining', 1980, 'Horror', 'A family heads to an isolated hotel for the winter, where a sinister presence influences the father.', 'Stanley Kubrick', 146),
('Spirited Away', 2001, 'Animation', 'A young girl becomes trapped in a mysterious, supernatural world.', 'Hayao Miyazaki', 125),
('Blade Runner', 1982, 'Sci-Fi', 'A blade runner must pursue and terminate replicants who have escaped to Earth.', 'Ridley Scott', 117),
('The Usual Suspects', 1995, 'Mystery', 'A sole survivor tells of the twists and turns that led to a horrific gun battle.', 'Bryan Singer', 106),
('Se7en', 1995, 'Thriller', 'Two detectives hunt a serial killer who uses the seven deadly sins as his modus operandi.', 'David Fincher', 127),
('The Pianist', 2002, 'Biography', 'A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto.', 'Roman Polanski', 150),
('Life Is Beautiful', 1997, 'Comedy', 'A Jewish father shields his son from the horrors of a Nazi concentration camp.', 'Roberto Benigni', 116),
('Up', 2009, 'Animation', 'An old man ties thousands of balloons to his house and flies to South America.', 'Pete Docter, Bob Peterson', 96),
('Ratatouille', 2007, 'Animation', 'A rat who can cook makes an unusual alliance with a young kitchen worker.', 'Brad Bird, Jan Pinkava', 111),
('The Pursuit of Happyness', 2006, 'Drama', 'A struggling salesman takes custody of his son as he is poised to begin a life-changing career.', 'Gabriele Muccino', 117),
('WALL-E', 2008, 'Animation', 'In the distant future, a small waste-collecting robot embarks on a space journey.', 'Andrew Stanton', 98),
('Deadpool', 2016, 'Action', 'A former Special Forces operative becomes a mercenary with a twisted sense of humor.', 'Tim Miller', 108),
('Zootopia', 2016, 'Animation', 'A bunny cop and a cynical con artist fox must work together to uncover a conspiracy.', 'Byron Howard, Rich Moore, Jared Bush', 108),
('Inglourious Basterds', 2009, 'War', 'A group of Jewish-American soldiers plot to assassinate Nazi leaders in WWII.', 'Quentin Tarantino', 153),
('Logan', 2017, 'Action', 'In a future where mutants are nearly extinct, an elderly Wolverine and a young mutant seek refuge.', 'James Mangold', 137),
('The Revenant', 2015, 'Adventure', 'A frontiersman on a fur trading expedition fights for survival after being mauled by a bear.', 'Alejandro G. Iñárritu', 156),
('Frozen', 2013, 'Animation', 'A young princess sets out on a journey with an iceman to find her estranged sister.', 'Chris Buck, Jennifer Lee', 102),
('Moana', 2016, 'Animation', 'An adventurous teenager sails out on a daring mission to save her people.', 'Ron Clements, John Musker, Don Hall, Chris Williams', 107),
('Shrek', 2001, 'Animation', 'An ogre rescues a princess, only to find out that she is cursed.', 'Andrew Adamson, Vicky Jenson', 90),
('Mad Max: Fury Road', 2015, 'Action', 'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler.', 'George Miller', 120),
('Joker', 2019, 'Crime', 'In Gotham City, a mentally troubled comedian embarks on a downward spiral of social revolution.', 'Todd Phillips', 122),
('Bohemian Rhapsody', 2018, 'Biography', 'The story of the legendary rock band Queen and lead singer Freddie Mercury.', 'Bryan Singer', 134),
('Black Panther', 2018, 'Action', 'TChalla returns home to take his rightful place as king of Wakanda.', 'Ryan Coogler', 134),
('Harry Potter and the Sorcerers Stone', 2001, 'Fantasy', 'A young boy discovers he is a wizard on his eleventh birthday.', 'Chris Columbus', 152),
('The Hunger Games', 2012, 'Sci-Fi', 'Katniss Everdeen voluntarily takes her sisters place in a deadly televised competition.', 'Gary Ross', 142),
('The Twilight Saga: Breaking Dawn - Part 2', 2012, 'Fantasy', 'After the birth of Renesmee, the Cullens gather other vampire clans.', 'Bill Condon', 115),
('Captain Marvel', 2019, 'Action', 'Carol Danvers becomes one of the universes most powerful heroes.', 'Anna Boden, Ryan Fleck', 123),
('Doctor Strange', 2016, 'Fantasy', 'A surgeon gains mystical powers after a car accident ruins his career.', 'Scott Derrickson', 115),
('Thor: Ragnarok', 2017, 'Action', 'Thor must escape the alien planet Sakaar in time to save Asgard from Hela.', 'Taika Waititi', 130),
('Iron Man', 2008, 'Action', 'After being held captive, Tony Stark builds a suit of armor to fight injustice.', 'Jon Favreau', 126),
('Guardians of the Galaxy', 2014, 'Adventure', 'A group of intergalactic criminals must pull together to stop a fanatical warrior.', 'James Gunn', 121),
('Ant-Man', 2015, 'Action', 'Armed with a suit that allows him to shrink, a thief must aid his mentor in protecting its secret.', 'Peyton Reed', 117),
('Spider-Man: Homecoming', 2017, 'Action', 'Peter Parker balances his life as an ordinary high school student with his superhero alter-ego.', 'Jon Watts', 133),
('The Lion King', 2019, 'Animation', 'After the murder of his father, a young lion prince flees his kingdom.', 'Jon Favreau', 118),
('Cinderella', 2015, 'Fantasy', 'A kind girl attends a ball at the castle with the help of her fairy godmother.', 'Kenneth Branagh', 105),
('Beauty and the Beast', 2017, 'Fantasy', 'A young woman is imprisoned in an enchanted castle by a beast.', 'Bill Condon', 129),
('Aladdin', 2019, 'Adventure', 'A kind-hearted street urchin vies for the love of a beautiful princess.', 'Guy Ritchie', 128),
('Maleficent', 2014, 'Fantasy', 'A vengeful fairy is driven to curse an infant princess.', 'Robert Stromberg', 97),
('The Jungle Book', 2016, 'Adventure', 'A man-cub named Mowgli embarks on a journey of self-discovery.', 'Jon Favreau', 106),
('Alice in Wonderland', 2010, 'Fantasy', 'A young girl falls into a rabbit hole and enters a world of whimsical characters.', 'Tim Burton', 108)
('A Quiet Place', 2018, 'Horror', 'In a post-apocalyptic world, a family is forced to live in silence.', 'John Krasinski', 90),
('Get Out', 2017, 'Horror', 'A young African-American visits his white girlfriends parents for the weekend.', 'Jordan Peele', 104),
('Parasite', 2019, 'Thriller', 'A poor family schemes to become employed by a wealthy family by infiltrating their household.', 'Bong Joon Ho', 132),
('Her', 2013, 'Romance', 'A lonely writer develops an unlikely relationship with an operating system.', 'Spike Jonze', 126),
('The Shape of Water', 2017, 'Fantasy', 'A mute woman forms a relationship with a mysterious aquatic creature.', 'Guillermo del Toro', 123),
('The Irishman', 2019, 'Crime', 'A mob hitman recalls his possible involvement with the slaying of Jimmy Hoffa.', 'Martin Scorsese', 209),
('No Country for Old Men', 2007, 'Thriller', 'A hunter stumbles upon a drug deal gone wrong and a bag of cash.', 'Ethan Coen, Joel Coen', 122),
('The Lobster', 2015, 'Comedy', 'In a dystopian future, single people are transformed into animals if they fail to find a mate.', 'Yorgos Lanthimos', 119),
('Moonlight', 2016, 'Drama', 'A young African-American man grapples with his identity and sexuality while growing up in Miami.', 'Barry Jenkins', 111),
('Lady Bird', 2017, 'Comedy', 'An artistically inclined seventeen-year-old comes of age in Sacramento, California.', 'Greta Gerwig', 94),
('Call Me by Your Name', 2017, 'Romance', 'In 1980s Italy, a romance blossoms between a seventeen-year-old student and an older man.', 'Luca Guadagnino', 132),
('The Farewell', 2019, 'Drama', 'A Chinese family discovers their grandmother has only a short time left to live.', 'Lulu Wang', 100),
('Jojo Rabbit', 2019, 'Comedy', 'A young boy in Nazi Germany discovers his mother is hiding a Jewish girl.', 'Taika Waititi', 108),
('Knives Out', 2019, 'Mystery', 'A detective investigates the death of a patriarch of an eccentric, combative family.', 'Rian Johnson', 130),
('Little Women', 2019, 'Drama', 'Jo March reflects back and forth on her life, telling the beloved story of the March sisters.', 'Greta Gerwig', 135),
('Once Upon a Time in Hollywood', 2019, 'Comedy', 'A faded television actor and his stunt double strive to achieve fame in the film industry.', 'Quentin Tarantino', 161),
('Marriage Story', 2019, 'Drama', 'Noah Baumbachs incisive and compassionate look at a marriage breaking up.', 'Noah Baumbach', 137),
('The Lighthouse', 2019, 'Horror', 'Two lighthouse keepers try to maintain their sanity while living on a remote island.', 'Robert Eggers', 109),
('1917', 2019, 'War', 'Two British soldiers must deliver a message to stop a deadly attack during WWI.', 'Sam Mendes', 119),
('Portrait of a Lady on Fire', 2019, 'Romance', 'On an isolated island in Brittany, a female painter is obliged to paint a wedding portrait.', 'Céline Sciamma', 122),
('Judas and the Black Messiah', 2021, 'Biography', 'Bill ONeal infiltrates the Black Panther Party to gather intelligence on Chairman Fred Hampton.', 'Shaka King', 126),
('Soul', 2020, 'Animation', 'A musician who has lost his passion for music is transported out of his body.', 'Pete Docter, Kemp Powers', 100),
('Tenet', 2020, 'Sci-Fi', 'A secret agent is given a single word as his weapon to prevent the onset of World War III.', 'Christopher Nolan', 150),
('Minari', 2020, 'Drama', 'A Korean-American family moves to an Arkansas farm in search of their own American Dream.', 'Lee Isaac Chung', 115),
('Sound of Metal', 2019, 'Drama', 'A drummer begins to lose his hearing and must come to grips with a future that will be filled with silence.', 'Darius Marder', 120),
('Nomadland', 2020, 'Drama', 'A woman in her sixties embarks on a journey through the American West, living as a modern-day nomad.', 'Chloé Zhao', 108),
('Promising Young Woman', 2020, 'Thriller', 'A young woman haunted by a tragedy in her past takes revenge on predatory men.', 'Emerald Fennell', 113),
('The Trial of the Chicago 7', 2020, 'History', 'The story of 7 people on trial stemming from various charges surrounding the uprising at the 1968 Democratic National Convention.', 'Aaron Sorkin', 130),
('The Father', 2020, 'Drama', 'A man refuses all assistance from his daughter as he ages.', 'Florian Zeller', 97),
('Mank', 2020, 'Biography', '1930s Hollywood is reevaluated through the eyes of scathing social critic and alcoholic screenwriter Herman J. Mankiewicz.', 'David Fincher', 131),
('Dune', 2021, 'Sci-Fi', 'Paul Atreides leads nomadic tribes in a battle to control the desert planet Arrakis.', 'Denis Villeneuve', 155),
('The Power of the Dog', 2021, 'Drama', 'A charismatic rancher inspires fear and awe in those around him.', 'Jane Campion', 126),
('West Side Story', 2021, 'Musical', 'An adaptation of the 1957 musical, exploring forbidden love and rivalry between gangs.', 'Steven Spielberg', 156),
('CODA', 2021, 'Drama', 'As a CODA (Child of Deaf Adults), Ruby is the only hearing person in her deaf family.', 'Sian Heder', 111),
('King Richard', 2021, 'Biography', 'A look at how tennis superstars Venus and Serena Williams became who they are after the coaching from their father Richard Williams.', 'Reinaldo Marcus Green', 144),
('Encanto', 2021, 'Animation', 'A Colombian teenage girl has to face the frustration of being the only member of her family without magical powers.', 'Jared Bush, Byron Howard, Charise Castro Smith', 99),
('The Lost Daughter', 2021, 'Drama', 'A womans beach vacation takes a dark turn when she begins to confront the troubles of her past.', 'Maggie Gyllenhaal', 121),
('Spencer', 2021, 'Biography', 'During her Christmas holidays with the royal family, Diana decides to leave her marriage to Prince Charles.', 'Pablo Larraín', 117),
('Nightmare Alley', 2021, 'Thriller', 'An ambitious carny with a talent for manipulating people hooks up with a female psychiatrist who is even more dangerous than he is.', 'Guillermo del Toro', 150),
('Tick, Tick... Boom!', 2021, 'Musical', 'On the cusp of his 30th birthday, a promising theater composer navigates love, friendship, and the pressures of life.', 'Lin-Manuel Miranda', 120),
('Drive My Car', 2021, 'Drama', 'After his wifes death, Yusuke is offered to direct a production of Uncle Vanya in Hiroshima.', 'Ryusuke Hamaguchi', 179),
('Licorice Pizza', 2021, 'Romance', 'The story of Alana Kane and Gary Valentine growing up, running around, and going through the treacherous navigation of first love.', 'Paul Thomas Anderson', 133),
('Gone with the Wind', 1939, 'Drama', 'A Southern belle struggles during and after the Civil War.', 'Victor Fleming', 238),
('Citizen Kane', 1941, 'Drama', 'The rise and fall of a publishing tycoon.', 'Orson Welles', 119),
('Metropolis', 1927, 'Sci-Fi', 'In a futuristic city, the wealthy and workers clash.', 'Fritz Lang', 148),
('Vertigo', 1958, 'Thriller', 'A detective develops a dangerous obsession.', 'Alfred Hitchcock', 128),
('Psycho', 1960, 'Horror', 'A secretary on the run checks into a secluded motel.', 'Alfred Hitchcock', 109),
('The Seven Samurai', 1954, 'Adventure', 'Villagers hire seven samurai to defend them.', 'Akira Kurosawa', 207),
('Rear Window', 1954, 'Thriller', 'A photographer spies on his neighbors from his apartment window.', 'Alfred Hitchcock', 112),
('It Happened One Night', 1934, 'Romance', 'A runaway heiress meets a roguish reporter.', 'Frank Capra', 105),
('Avatar: The Way of Water', 2022, 'Sci-Fi', 'Jake Sully must protect his family on Pandora.', 'James Cameron', 192),
('Dune', 2021, 'Sci-Fi', 'A noble family becomes embroiled in interstellar conflict over spice.', 'Denis Villeneuve', 155),
('Shang-Chi and the Legend of the Ten Rings', 2021, 'Action', 'A martial artist confronts his past to stop a mysterious organization.', 'Destin Daniel Cretton', 132),
('No Time to Die', 2021, 'Action', 'James Bond comes out of retirement to face a dangerous new villain.', 'Cary Joji Fukunaga', 163),
('Kubo and the Two Strings', 2016, 'Animation', 'A boy with a magical instrument embarks on a journey to defeat an evil spirit.', 'Travis Knight', 101),
('How to Train Your Dragon', 2010, 'Animation', 'A young Viking befriends a dragon to challenge societal norms.', 'Dean DeBlois, Chris Sanders', 98),
('Finding Nemo', 2003, 'Animation', 'A clownfish searches for his son in the ocean.', 'Andrew Stanton', 100),
('Big Hero 6', 2014, 'Animation', 'A robotics prodigy and his friends protect San Fransokyo from a masked villain.', 'Don Hall, Chris Williams', 102),
('Coraline', 2009, 'Animation', 'A girl discovers an alternate world with dark secrets.', 'Henry Selick', 100),
('Superbad', 2007, 'Comedy', 'Two high school friends have a wild night before graduation.', 'Greg Mottola', 113),
('The Hangover', 2009, 'Comedy', 'Three friends wake up in Las Vegas with no memory of the previous night.', 'Todd Phillips', 100),
('Bridesmaids', 2011, 'Comedy', 'A woman competes with her best friend’s new maid of honor.', 'Paul Feig', 125),
('Monty Python and the Holy Grail', 1975, 'Comedy', 'A humorous take on King Arthur’s quest for the Holy Grail.', 'Terry Gilliam, Terry Jones', 91),
('The Bourne Identity', 2002, 'Action', 'An amnesiac man uncovers his identity while evading assassins.', 'Doug Liman', 119),
('The Raid: Redemption', 2011, 'Action', 'A SWAT team fights through a gang-infested building.', 'Gareth Evans', 101),
('300', 2006, 'Action', 'A small force of Spartans battles the Persian army.', 'Zack Snyder', 117),
('Skyfall', 2012, 'Action', 'James Bond investigates attacks on MI6 while confronting his past.', 'Sam Mendes', 143),
('A Nightmare on Elm Street', 1984, 'Horror', 'A demon stalks teenagers in their dreams.', 'Wes Craven', 91),
('Midsommar', 2019, 'Horror', 'A grieving woman joins a sinister pagan festival in Sweden.', 'Ari Aster', 148),
('The Babadook', 2014, 'Horror', 'A sinister entity torments a grieving mother and her son.', 'Jennifer Kent', 94),
('Scream', 1996, 'Horror', 'A masked killer terrorizes high school students.', 'Wes Craven', 111),
('Amélie', 2001, 'Romance', 'A whimsical woman improves the lives of people around her.', 'Jean-Pierre Jeunet', 122),
('Pan’s Labyrinth', 2006, 'Fantasy', 'A girl discovers a magical world amidst the Spanish Civil War.', 'Guillermo del Toro', 118),
('Oldboy', 2003, 'Thriller', 'A man seeks revenge after being imprisoned for 15 years.', 'Park Chan-wook', 120),
('City of God', 2002, 'Crime', 'The lives of two young men in a violent Rio de Janeiro favela.', 'Fernando Meirelles, Kátia Lund', 130),
('Eternal Sunshine of the Spotless Mind', 2004, 'Romance', 'A couple undergoes a procedure to erase memories of each other.', 'Michel Gondry', 108),
('Lost in Translation', 2003, 'Drama', 'Two strangers form a connection in Tokyo.', 'Sofia Coppola', 102),
('The Florida Project', 2017, 'Drama', 'A girl experiences childhood in the shadow of Disney World.', 'Sean Baker', 111),
('The Witch', 2015, 'Horror', 'A family in 1630s New England encounters sinister forces.', 'Robert Eggers', 92),
('The Theory of Everything', 2014, 'Biography', 'The life and work of physicist Stephen Hawking.', 'James Marsh', 123),
('Lincoln', 2012, 'Biography', 'The story of Abraham Lincoln’s efforts to pass the 13th Amendment.', 'Steven Spielberg', 150),
('Steve Jobs', 2015, 'Biography', 'The life of Apple co-founder Steve Jobs is explored through key product launches.', 'Danny Boyle', 122),
('Rocketman', 2019, 'Biography', 'A musical journey through Elton John’s breakthrough years.', 'Dexter Fletcher', 121),
('The Greatest Showman', 2017, 'Musical', 'The story of P.T. Barnum’s creation of the circus.', 'Michael Gracey', 105),
('Les Misérables', 2012, 'Musical', 'A former convict seeks redemption in post-revolutionary France.', 'Tom Hooper', 158),
('Mamma Mia!', 2008, 'Musical', 'A bride-to-be invites three men from her mother’s past to her wedding.', 'Phyllida Lloyd', 108),
('Prisoners', 2013, 'Thriller', 'A father takes matters into his own hands when his daughter is abducted.', 'Denis Villeneuve', 153),
('Nightcrawler', 2014, 'Thriller', 'A conman becomes a crime journalist in Los Angeles.', 'Dan Gilroy', 117),
('Gone Girl', 2014, 'Thriller', 'A husband becomes the suspect when his wife disappears.', 'David Fincher', 149),
('The Chronicles of Narnia: The Lion, the Witch and the Wardrobe', 2005, 'Fantasy', 'Four siblings discover a magical world through a wardrobe.', 'Andrew Adamson', 143),
('The Golden Compass', 2007, 'Fantasy', 'A young girl in a parallel world uncovers a sinister plot.', 'Chris Weitz', 113),
('Free Solo', 2018, 'Documentary', 'A climber attempts to scale El Capitan without ropes.', 'Elizabeth Chai Vasarhelyi, Jimmy Chin', 100),
('Won’t You Be My Neighbor?', 2018, 'Documentary', 'A look at the life and legacy of Fred Rogers.', 'Morgan Neville', 94),
('13th', 2016, 'Documentary', 'An exploration of racial inequality in the U.S. prison system.', 'Ava DuVernay', 100)
('The Maltese Falcon', 1941, 'Mystery', 'A private detective searches for a priceless artifact.', 'John Huston', 100),
('Lawrence of Arabia', 1962, 'Drama', 'The story of T.E. Lawrence and his role in the Arab Revolt.', 'David Lean', 222),
('Dr. Strangelove', 1964, 'Comedy', 'A satirical look at Cold War politics and nuclear annihilation.', 'Stanley Kubrick', 95),
('Some Like It Hot', 1959, 'Comedy', 'Two musicians disguise themselves as women to escape gangsters.', 'Billy Wilder', 121),
('12 Angry Men', 1957, 'Drama', 'A jury debates the guilt of a young defendant in a murder trial.', 'Sidney Lumet', 96),
('Everything Everywhere All at Once', 2022, 'Sci-Fi', 'A woman explores parallel universes to save the multiverse.', 'Daniel Kwan, Daniel Scheinert', 139),
('The Batman', 2022, 'Action', 'Batman uncovers corruption in Gotham while pursuing the Riddler.', 'Matt Reeves', 176),
('Top Gun: Maverick', 2022, 'Action', 'A veteran pilot trains a new generation for a daring mission.', 'Joseph Kosinski', 131),
('Joker', 2019, 'Drama', 'The origin story of the iconic villain in Gotham City.', 'Todd Phillips', 122),
('The Secret of NIMH', 1982, 'Animation', 'A field mouse enlists the help of super-intelligent rats to save her family.', 'Don Bluth', 82),
('Castle in the Sky', 1986, 'Animation', 'Two kids search for a mythical floating city.', 'Hayao Miyazaki', 124),
('The Iron Giant', 1999, 'Animation', 'A boy befriends a giant robot in 1950s America.', 'Brad Bird', 86),
('Zootopia', 2016, 'Animation', 'A bunny cop and a con artist fox solve a city mystery.', 'Byron Howard, Rich Moore', 108),
('Ex Machina', 2015, 'Sci-Fi', 'A programmer tests an advanced AI in a remote facility.', 'Alex Garland', 108),
('Blade Runner 2049', 2017, 'Sci-Fi', 'A new Blade Runner uncovers secrets that could change humanity.', 'Denis Villeneuve', 163),
('Arrival', 2016, 'Sci-Fi', 'A linguist communicates with extraterrestrials to prevent a global crisis.', 'Denis Villeneuve', 116),
('Her', 2013, 'Sci-Fi', 'A lonely man forms a bond with an AI operating system.', 'Spike Jonze', 126),
('Napoleon Dynamite', 2004, 'Comedy', 'A quirky high schooler navigates life and elections.', 'Jared Hess', 96),
('Office Space', 1999, 'Comedy', 'An office worker rebels against corporate culture.', 'Mike Judge', 89),
('Tropic Thunder', 2008, 'Comedy', 'Actors in a war movie find themselves in real danger.', 'Ben Stiller', 107),
('Anchorman: The Legend of Ron Burgundy', 2004, 'Comedy', 'A 1970s news anchor clashes with his new female colleague.', 'Adam McKay', 94),
('Mad Max: Fury Road', 2015, 'Action', 'A post-apocalyptic road warrior helps a group escape a tyrant.', 'George Miller', 120),
('John Wick: Chapter 4', 2023, 'Action', 'John Wick seeks revenge against the High Table.', 'Chad Stahelski', 169),
('The Revenant', 2015, 'Adventure', 'A frontiersman survives betrayal and harsh wilderness to seek revenge.', 'Alejandro G. Iñárritu', 156),
('The Conjuring', 2013, 'Horror', 'Paranormal investigators help a family haunted by a dark entity.', 'James Wan', 112),
('Get Out', 2017, 'Horror', 'A young Black man discovers disturbing secrets at his girlfriend’s family estate.', 'Jordan Peele', 104),
('The Exorcist', 1973, 'Horror', 'A young girl becomes possessed by a demonic force.', 'William Friedkin', 122),
('The Ring', 2002, 'Horror', 'A cursed videotape leads to a week of terror.', 'Gore Verbinski', 115),
('Bohemian Rhapsody', 2018, 'Biography', 'The life and career of Queen frontman Freddie Mercury.', 'Bryan Singer', 134),
('A Beautiful Mind', 2001, 'Biography', 'The life of mathematician John Nash and his struggles with schizophrenia.', 'Ron Howard', 135),
('Schindler’s List', 1993, 'Biography', 'A businessman saves the lives of Jews during the Holocaust.', 'Steven Spielberg', 195),
('The Hobbit: An Unexpected Journey', 2012, 'Fantasy', 'Bilbo Baggins sets out on a journey with a group of dwarves.', 'Peter Jackson', 169),
('Doctor Strange', 2016, 'Fantasy', 'A surgeon learns mystic arts to protect the world from dark forces.', 'Scott Derrickson', 115),
('The Shape of Water', 2017, 'Fantasy', 'A mute woman bonds with an aquatic creature in a government lab.', 'Guillermo del Toro', 123),
('The Social Dilemma', 2020, 'Documentary', 'A look at the dangerous impacts of social media on society.', 'Jeff Orlowski', 94),
('My Octopus Teacher', 2020, 'Documentary', 'A filmmaker forms a bond with an octopus in the wild.', 'Pippa Ehrlich, James Reed', 85),
('Apollo 11', 2019, 'Documentary', 'The historic mission to land on the moon, as told through archival footage.', 'Todd Douglas Miller', 93),
('The Lives of Others', 2006, 'Drama', 'An East German agent surveils a playwright and questions his loyalties.', 'Florian Henckel von Donnersmarck', 137),
('Crouching Tiger, Hidden Dragon', 2000, 'Fantasy', 'Martial artists search for a stolen legendary sword.', 'Ang Lee', 120),
('The Handmaiden', 2016, 'Thriller', 'A con artist and a pickpocket plot against a wealthy heiress.', 'Park Chan-wook', 145),
('Train to Busan', 2016, 'Horror', 'Passengers on a train fight to survive a zombie outbreak.', 'Yeon Sang-ho', 118),
('Lady Bird', 2017, 'Drama', 'A teenager navigates life, love, and ambition in Sacramento.', 'Greta Gerwig', 93),
('Moonlight', 2016, 'Drama', 'A young Black man grapples with his identity and sexuality.', 'Barry Jenkins', 111),
('Sound of Metal', 2019, 'Drama', 'A drummer loses his hearing and adjusts to a new life.', 'Darius Marder', 120),
('Whiplash', 2014, 'Drama', 'A young drummer is pushed to his limits by a demanding instructor.', 'Damien Chazelle', 106)
('Sunset Boulevard', 1950, 'Drama', 'A faded silent film star lures a young screenwriter into her delusional world.', 'Billy Wilder', 110),
('Rebel Without a Cause', 1955, 'Drama', 'A troubled teenager struggles to find meaning in his life.', 'Nicholas Ray', 111),
('The Bridge on the River Kwai', 1957, 'War', 'British prisoners of war build a bridge under Japanese captivity.', 'David Lean', 161),
('All About Eve', 1950, 'Drama', 'A young actress schemes to take over an aging star’s career.', 'Joseph L. Mankiewicz', 138),
('The Day the Earth Stood Still', 1951, 'Sci-Fi', 'An alien visitor warns Earth of impending doom.', 'Robert Wise', 92),
('Avatar: The Way of Water', 2022, 'Sci-Fi', 'Jake Sully protects his family amidst a new threat on Pandora.', 'James Cameron', 192),
('Black Panther: Wakanda Forever', 2022, 'Action', 'The Wakandan leaders fight to protect their nation after King T’Challa’s death.', 'Ryan Coogler', 161),
('Spider-Man: No Way Home', 2021, 'Action', 'Peter Parker faces multiverse villains after his identity is exposed.', 'Jon Watts', 148),
('Dune', 2021, 'Sci-Fi', 'A noble family battles to control a desert planet and its resources.', 'Denis Villeneuve', 155),
('No Time to Die', 2021, 'Action', 'James Bond comes out of retirement to face a deadly villain.', 'Cary Joji Fukunaga', 163),
('Ratatouille', 2007, 'Animation', 'A rat dreams of becoming a chef in Paris.', 'Brad Bird', 111),
('Frozen II', 2019, 'Animation', 'Elsa and Anna uncover the origins of Elsa’s powers.', 'Chris Buck, Jennifer Lee', 103),
('Soul', 2020, 'Animation', 'A jazz musician discovers the essence of life.', 'Pete Docter, Kemp Powers', 100),
('Kubo and the Two Strings', 2016, 'Animation', 'A boy with magical powers embarks on an epic quest.', 'Travis Knight', 102),
('Coco', 2017, 'Animation', 'A young musician explores the Land of the Dead to learn about his family.', 'Lee Unkrich, Adrian Molina', 105),
('Prisoners', 2013, 'Thriller', 'A father takes matters into his own hands when his daughter is kidnapped.', 'Denis Villeneuve', 153),
('The Girl with the Dragon Tattoo', 2011, 'Thriller', 'A journalist and a hacker investigate a wealthy family’s dark secrets.', 'David Fincher', 158),
('The Prestige', 2006, 'Thriller', 'Rival magicians engage in a deadly battle of one-upmanship.', 'Christopher Nolan', 130),
('Sicario', 2015, 'Thriller', 'An FBI agent joins a task force to combat drug cartels.', 'Denis Villeneuve', 121),
('Gone Baby Gone', 2007, 'Thriller', 'Private detectives investigate a young girl’s disappearance.', 'Ben Affleck', 114),
('The Notebook', 2004, 'Romance', 'A love story spanning decades between two people from different worlds.', 'Nick Cassavetes', 123),
('Before Sunrise', 1995, 'Romance', 'Two strangers share a night of connection in Vienna.', 'Richard Linklater', 101),
('Silver Linings Playbook', 2012, 'Romance', 'Two people with emotional struggles find comfort in each other.', 'David O. Russell', 122),
('Crazy Rich Asians', 2018, 'Romance', 'A woman discovers her boyfriend’s wealthy background while visiting Singapore.', 'Jon M. Chu', 120),
('Pride & Prejudice', 2005, 'Romance', 'Elizabeth Bennet navigates love and social expectations in Regency England.', 'Joe Wright', 129),
('It Follows', 2014, 'Horror', 'A young woman is pursued by a mysterious entity after a sexual encounter.', 'David Robert Mitchell', 100),
('A Quiet Place Part II', 2021, 'Horror', 'The Abbott family continues their fight for survival against sound-sensitive creatures.', 'John Krasinski', 97),
('Midsommar', 2019, 'Horror', 'A group of friends encounters a pagan cult in Sweden.', 'Ari Aster', 147),
('The Cabin in the Woods', 2012, 'Horror', 'Five friends discover sinister forces at play during a weekend getaway.', 'Drew Goddard', 95),
('Barbarian', 2022, 'Horror', 'A woman’s rental home holds horrifying secrets.', 'Zach Cregger', 102),
('Parasite', 2019, 'Drama', 'A poor family infiltrates a wealthy household with unexpected consequences.', 'Bong Joon-ho', 132),
('Oldboy', 2003, 'Thriller', 'A man seeks revenge after being imprisoned for 15 years without explanation.', 'Park Chan-wook', 120),
('Amélie', 2001, 'Romance', 'A quirky young woman changes the lives of people around her in Paris.', 'Jean-Pierre Jeunet', 122),
('City of God', 2002, 'Crime', 'The rise of organized crime in the favelas of Rio de Janeiro.', 'Fernando Meirelles, Kátia Lund', 130),
('Spirited Away', 2001, 'Animation', 'A girl must navigate a mystical world to save her parents.', 'Hayao Miyazaki', 125),
('Juno', 2007, 'Comedy', 'A teenager navigates an unplanned pregnancy with humor and wit.', 'Jason Reitman', 96),
('Donnie Darko', 2001, 'Sci-Fi', 'A troubled teenager confronts visions of a mysterious figure in a rabbit suit.', 'Richard Kelly', 113),
('Little Miss Sunshine', 2006, 'Comedy', 'A dysfunctional family takes a road trip for a children’s beauty pageant.', 'Jonathan Dayton, Valerie Faris', 101),
('The Florida Project', 2017, 'Drama', 'A young girl and her mother navigate life on the edge of poverty.', 'Sean Baker', 111),
('Eternal Sunshine of the Spotless Mind', 2004, 'Romance', 'A couple undergoes a procedure to erase memories of their relationship.', 'Michel Gondry', 108),
('Won’t You Be My Neighbor?', 2018, 'Documentary', 'A look at the life and legacy of Mr. Rogers.', 'Morgan Neville', 94),
('Free Solo', 2018, 'Documentary', 'A climber attempts a death-defying ascent of El Capitan without ropes.', 'Elizabeth Chai Vasarhelyi, Jimmy Chin', 100),
('13th', 2016, 'Documentary', 'Exploring the intersection of race, justice, and mass incarceration in America.', 'Ava DuVernay', 100),
('Jiro Dreams of Sushi', 2011, 'Documentary', 'The life and work of a sushi master in Japan.', 'David Gelb', 81),
('Super Size Me', 2004, 'Documentary', 'A man eats only McDonald’s for 30 days to explore its health effects.', 'Morgan Spurlock', 100)
('An American in Paris', 1951, 'Musical', 'An ex-GI pursues his dreams of art and love in Paris.', 'Vincente Minnelli', 114),
('Dr. Zhivago', 1965, 'Romance', 'A love story unfolds during the Russian Revolution.', 'David Lean', 197),
('The Philadelphia Story', 1940, 'Romantic Comedy', 'A socialite’s wedding plans are upended by her ex-husband and a reporter.', 'George Cukor', 112),
('12 Angry Men', 1957, 'Drama', 'A jury deliberates on the guilt of a young defendant.', 'Sidney Lumet', 96),
('Touch of Evil', 1958, 'Crime', 'A corrupt cop’s actions lead to murder and deceit.', 'Orson Welles', 112),
('The Fabelmans', 2022, 'Drama', 'A young filmmaker explores family secrets and discovers his passion for movies.', 'Steven Spielberg', 151),
('Everything Everywhere All At Once', 2022, 'Sci-Fi', 'A woman navigates multiple universes to save her family.', 'Daniel Kwan, Daniel Scheinert', 140),
('Top Gun: Maverick', 2022, 'Action', 'Pete Mitchell trains a new generation of pilots.', 'Joseph Kosinski', 130),
('The Batman', 2022, 'Action', 'Batman investigates a series of murders in Gotham City.', 'Matt Reeves', 176),
('Glass Onion: A Knives Out Mystery', 2022, 'Mystery', 'Detective Benoit Blanc solves a murder on a billionaire’s private island.', 'Rian Johnson', 139),
('Encanto', 2021, 'Animation', 'A magical family in Colombia faces challenges when their powers are threatened.', 'Jared Bush, Byron Howard', 102),
('Sing 2', 2021, 'Animation', 'Buster Moon and his friends prepare for a major show in a big city.', 'Garth Jennings', 110),
('Zootopia', 2016, 'Animation', 'A rabbit cop and a fox con artist solve a conspiracy.', 'Byron Howard, Rich Moore', 108),
('Despicable Me', 2010, 'Animation', 'A villain’s life changes when he adopts three young girls.', 'Pierre Coffin, Chris Renaud', 95),
('The Secret Life of Pets', 2016, 'Animation', 'A group of pets embarks on an adventure in New York City.', 'Chris Renaud', 87),
('The Matrix Resurrections', 2021, 'Sci-Fi', 'Neo rediscovers his purpose in a new version of the Matrix.', 'Lana Wachowski', 148),
('Interstellar', 2014, 'Sci-Fi', 'A team of explorers searches for a new home for humanity.', 'Christopher Nolan', 169),
('The Shape of Water', 2017, 'Fantasy', 'A mute woman forms a bond with a mysterious aquatic creature.', 'Guillermo del Toro', 123),
('Ex Machina', 2014, 'Sci-Fi', 'A programmer tests the capabilities of an advanced AI robot.', 'Alex Garland', 108),
('Snowpiercer', 2013, 'Sci-Fi', 'Survivors of a frozen Earth live aboard a perpetually moving train.', 'Bong Joon-ho', 126),
('Superbad', 2007, 'Comedy', 'Two high school friends try to party before graduation.', 'Greg Mottola', 113),
('Step Brothers', 2008, 'Comedy', 'Two immature adults are forced to live together as stepbrothers.', 'Adam McKay', 106),
('The Grand Budapest Hotel', 2014, 'Comedy', 'A concierge and his protégé become involved in a murder mystery.', 'Wes Anderson', 99),
('Jojo Rabbit', 2019, 'Comedy', 'A boy in Nazi Germany discovers his mother is hiding a Jewish girl.', 'Taika Waititi', 108),
('Napoleon Dynamite', 2004, 'Comedy', 'A socially awkward teenager navigates high school and family life.', 'Jared Hess', 96),
('The Lives of Others', 2006, 'Drama', 'A Stasi agent spies on a playwright in East Germany.', 'Florian Henckel von Donnersmarck', 137),
('Crouching Tiger, Hidden Dragon', 2000, 'Action', 'A stolen sword leads to love and betrayal in Qing Dynasty China.', 'Ang Lee', 120),
('Roma', 2018, 'Drama', 'A maid navigates life in 1970s Mexico City.', 'Alfonso Cuarón', 135),
('Pan’s Labyrinth', 2006, 'Fantasy', 'A girl discovers a magical world amidst post-Civil War Spain.', 'Guillermo del Toro', 118),
('Hero', 2002, 'Action', 'An assassin tells tales of his encounters with legendary warriors.', 'Zhang Yimou', 107),
('The Babadook', 2014, 'Horror', 'A mother and son are haunted by a sinister storybook.', 'Jennifer Kent', 94),
('Hereditary', 2018, 'Horror', 'A family uncovers dark secrets after their grandmother’s death.', 'Ari Aster', 127),
('Get Out', 2017, 'Horror', 'A Black man uncovers terrifying secrets at his girlfriend’s family estate.', 'Jordan Peele', 104),
('Us', 2019, 'Horror', 'A family is terrorized by doppelgängers.', 'Jordan Peele', 116),
('The Witch', 2015, 'Horror', 'A Puritan family faces supernatural threats in 1630s New England.', 'Robert Eggers', 92),
('Moonlight', 2016, 'Drama', 'A young Black man struggles with his identity and sexuality.', 'Barry Jenkins', 111),
('Lady Bird', 2017, 'Drama', 'A high school senior yearns for independence and clashes with her mother.', 'Greta Gerwig', 94),
('Manchester by the Sea', 2016, 'Drama', 'A man returns to his hometown after a family tragedy.', 'Kenneth Lonergan', 137),
('The Farewell', 2019, 'Drama', 'A family keeps a terminal diagnosis secret from their matriarch.', 'Lulu Wang', 100),
('Whiplash', 2014, 'Drama', 'A young drummer is pushed to the limit by his demanding music teacher.', 'Damien Chazelle', 107),
('The Social Dilemma', 2020, 'Documentary', 'An examination of the impact of social media on society.', 'Jeff Orlowski', 94),
('March of the Penguins', 2005, 'Documentary', 'The life cycle of emperor penguins in Antarctica.', 'Luc Jacquet', 80),
('Honeyland', 2019, 'Documentary', 'A beekeeper’s life changes when new neighbors arrive.', 'Tamara Kotevska, Ljubomir Stefanov', 89),
('The Last Dance', 2020, 'Documentary', 'Michael Jordan’s final season with the Chicago Bulls.', 'Jason Hehir', 500),
('Bowling for Columbine', 2002, 'Documentary', 'An exploration of gun violence in America.', 'Michael Moore', 120);