INSERT INTO movie_recommendation.movies (title, release_year, genre, description, director, duration) VALUES
('Inception', 2010, 'Sci-Fi', 'A skilled thief leads a team into the dreams of others.', 'Christopher Nolan', 148),
('The Shawshank Redemption', 1994, 'Drama', 'Two imprisoned men bond over years, finding solace and eventual redemption.', 'Frank Darabont', 142),
('The Godfather', 1972, 'Crime', 'The aging patriarch of an organized crime dynasty transfers control to his son.', 'Francis Ford Coppola', 175),
('The Dark Knight', 2008, 'Action', 'Batman battles the Joker, who unleashes chaos in Gotham City.', 'Christopher Nolan', 152),
('Pulp Fiction', 1994, 'Crime', 'The lives of two mob hitmen, a boxer, and a gangster intertwine in L.A.', 'Quentin Tarantino', 154),
('Forrest Gump', 1994, 'Drama', 'The presidencies of Kennedy and Johnson, events of Vietnam, and more unfold through the life of Forrest.', 'Robert Zemeckis', 142),
('The Matrix', 1999, 'Sci-Fi', 'A hacker discovers the world is a simulated reality and joins a rebellion.', 'Lana Wachowski, Lilly Wachowski', 136),
('Fight Club', 1999, 'Drama', 'An insomniac office worker forms an underground fight club with a soap salesman.', 'David Fincher', 139),
('Titanic', 1997, 'Romance', 'A young aristocrat falls in love with a kind but poor artist aboard the Titanic.', 'James Cameron', 195),
('Gladiator', 2000, 'Action', 'A betrayed Roman general seeks revenge against the corrupt emperor.', 'Ridley Scott', 155),
('The Lord of the Rings: The Fellowship of the Ring', 2001, 'Fantasy', 'A meek Hobbit and his companions set out on a journey to destroy a powerful ring.', 'Peter Jackson', 178),
('Star Wars: Episode IV - A New Hope', 1977, 'Sci-Fi', 'Luke Skywalker joins forces with a Jedi Knight to save the galaxy.', 'George Lucas', 121),
('The Lion King', 1994, 'Animation', 'A young lion prince flees his kingdom after the murder of his father.', 'Roger Allers, Rob Minkoff', 88),
('Back to the Future', 1985, 'Adventure', 'A teenager is sent back in time to 1955 and must ensure his parents fall in love.', 'Robert Zemeckis', 116),
('Jurassic Park', 1993, 'Adventure', 'A pragmatic paleontologist visits an amusement park with living dinosaurs.', 'Steven Spielberg', 127),
('The Avengers', 2012, 'Action', 'Earths mightiest heroes must come together to stop Loki and his army.', 'Joss Whedon', 143),
('Braveheart', 1995, 'History', 'Scottish warrior William Wallace leads his countrymen in a rebellion.', 'Mel Gibson', 178),
('The Social Network', 2010, 'Drama', 'The founding of Facebook, and the lawsuits that followed.', 'David Fincher', 120),
('Avengers: Endgame', 2019, 'Action', 'The Avengers assemble once more to undo the damage caused by Thanos.', 'Anthony Russo, Joe Russo', 181),
('The Silence of the Lambs', 1991, 'Thriller', 'A young FBI cadet must seek the help of an incarcerated cannibal killer.', 'Jonathan Demme', 118),
('Schindlers List', 1993, 'History', 'A German businessman saves the lives of more than a thousand Jewish refugees.', 'Steven Spielberg', 195),
('The Green Mile', 1999, 'Crime', 'The lives of guards on Death Row are affected by one of their charges.', 'Frank Darabont', 189),
('Interstellar', 2014, 'Sci-Fi', 'A team of explorers travel through a wormhole in space.', 'Christopher Nolan', 169),
('Saving Private Ryan', 1998, 'War', 'A group of U.S. soldiers go behind enemy lines to retrieve a paratrooper.', 'Steven Spielberg', 169),
('The Prestige', 2006, 'Mystery', 'Two stage magicians engage in a battle to create the ultimate illusion.', 'Christopher Nolan', 130),
('The Departed', 2006, 'Crime', 'An undercover cop and a mole in the police attempt to identify each other.', 'Martin Scorsese', 151),
('Whiplash', 2014, 'Drama', 'A promising young drummer enrolls at a cut-throat music conservatory.', 'Damien Chazelle', 106),
('Django Unchained', 2012, 'Western', 'With the help of a German bounty-hunter, a freed slave sets out to rescue his wife.', 'Quentin Tarantino', 165),
('The Wolf of Wall Street', 2013, 'Biography', 'The true story of Jordan Belfort, from a wealthy stockbroker to his downfall.', 'Martin Scorsese', 180),
('The Big Lebowski', 1998, 'Comedy', 'The Dude abides as he navigates life in L.A. after a mistaken identity case.', 'Joel Coen, Ethan Coen', 117),
('Spider-Man: Into the Spider-Verse', 2018, 'Animation', 'Teen Miles Morales becomes Spider-Man of his reality.', 'Bob Persichetti, Peter Ramsey, Rodney Rothman', 117),
('Toy Story', 1995, 'Animation', 'A cowboy doll is profoundly threatened when a new spaceman figure supplants him.', 'John Lasseter', 81),
('The Terminator', 1984, 'Action', 'A cyborg assassin is sent back in time to kill the mother of a future resistance leader.', 'James Cameron', 107),
('Alien', 1979, 'Sci-Fi', 'The crew of a spaceship encounters a deadly alien organism.', 'Ridley Scott', 117),
('Goodfellas', 1990, 'Crime', 'The rise and fall of a mob associate in the Italian-American crime syndicate.', 'Martin Scorsese', 146),
('Casablanca', 1942, 'Romance', 'A cynical expatriate finds a reason to fight the Nazis during WWII.', 'Michael Curtiz', 102),
('The Sound of Music', 1965, 'Musical', 'A woman leaves an Austrian convent to become a governess for a widower.', 'Robert Wise', 172),
('2001: A Space Odyssey', 1968, 'Sci-Fi', 'Humanity encounters a mysterious monolith that seems to affect human evolution.', 'Stanley Kubrick', 149),
('E.T. the Extra-Terrestrial', 1982, 'Sci-Fi', 'A troubled child summons the courage to help a friendly alien escape Earth.', 'Steven Spielberg', 115),
('The Grand Budapest Hotel', 2014, 'Comedy', 'A writer encounters the owner of a high-class hotel who recounts his adventures.', 'Wes Anderson', 99),
('Rocky', 1976, 'Drama', 'A small-time boxer gets a chance to fight the heavyweight champion.', 'John G. Avildsen', 120),
('La La Land', 2016, 'Romance', 'A jazz musician and an aspiring actress fall in love while pursuing their dreams.', 'Damien Chazelle', 128),
('Slumdog Millionaire', 2008, 'Drama', 'A Mumbai teen reflects on his life after being accused of cheating on a game show.', 'Danny Boyle', 120),
('The Intouchables', 2011, 'Biography', 'An aristocrat hires a young man from the projects to be his caregiver.', 'Olivier Nakache, Éric Toledano', 112),
('A Beautiful Mind', 2001, 'Biography', 'A brilliant mathematician struggles with schizophrenia.', 'Ron Howard', 135),
('Coco', 2017, 'Animation', 'A boy who dreams of becoming a musician embarks on a journey to the Land of the Dead.', 'Lee Unkrich, Adrian Molina', 105),
('The Incredibles', 2004, 'Animation', 'A family of undercover superheroes attempt to live a quiet suburban life.', 'Brad Bird', 115),
('The Shining', 1980, 'Horror', 'A family heads to an isolated hotel for the winter, where a sinister presence influences the father.', 'Stanley Kubrick', 146),
('Spirited Away', 2001, 'Animation', 'A young girl becomes trapped in a mysterious, supernatural world.', 'Hayao Miyazaki', 125),
('Blade Runner', 1982, 'Sci-Fi', 'A blade runner must pursue and terminate replicants who have escaped to Earth.', 'Ridley Scott', 117),
('The Usual Suspects', 1995, 'Mystery', 'A sole survivor tells of the twists and turns that led to a horrific gun battle.', 'Bryan Singer', 106),
('Se7en', 1995, 'Thriller', 'Two detectives hunt a serial killer who uses the seven deadly sins as his modus operandi.', 'David Fincher', 127),
('The Pianist', 2002, 'Biography', 'A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto.', 'Roman Polanski', 150),
('Life Is Beautiful', 1997, 'Comedy', 'A Jewish father shields his son from the horrors of a Nazi concentration camp.', 'Roberto Benigni', 116),
('Up', 2009, 'Animation', 'An old man ties thousands of balloons to his house and flies to South America.', 'Pete Docter, Bob Peterson', 96),
('Ratatouille', 2007, 'Animation', 'A rat who can cook makes an unusual alliance with a young kitchen worker.', 'Brad Bird, Jan Pinkava', 111),
('The Pursuit of Happyness', 2006, 'Drama', 'A struggling salesman takes custody of his son as he is poised to begin a life-changing career.', 'Gabriele Muccino', 117),
('WALL-E', 2008, 'Animation', 'In the distant future, a small waste-collecting robot embarks on a space journey.', 'Andrew Stanton', 98),
('Deadpool', 2016, 'Action', 'A former Special Forces operative becomes a mercenary with a twisted sense of humor.', 'Tim Miller', 108),
('Zootopia', 2016, 'Animation', 'A bunny cop and a cynical con artist fox must work together to uncover a conspiracy.', 'Byron Howard, Rich Moore, Jared Bush', 108),
('Inglourious Basterds', 2009, 'War', 'A group of Jewish-American soldiers plot to assassinate Nazi leaders in WWII.', 'Quentin Tarantino', 153),
('Logan', 2017, 'Action', 'In a future where mutants are nearly extinct, an elderly Wolverine and a young mutant seek refuge.', 'James Mangold', 137),
('The Revenant', 2015, 'Adventure', 'A frontiersman on a fur trading expedition fights for survival after being mauled by a bear.', 'Alejandro G. Iñárritu', 156),
('Frozen', 2013, 'Animation', 'A young princess sets out on a journey with an iceman to find her estranged sister.', 'Chris Buck, Jennifer Lee', 102),
('Moana', 2016, 'Animation', 'An adventurous teenager sails out on a daring mission to save her people.', 'Ron Clements, John Musker, Don Hall, Chris Williams', 107),
('Shrek', 2001, 'Animation', 'An ogre rescues a princess, only to find out that she is cursed.', 'Andrew Adamson, Vicky Jenson', 90),
('Mad Max: Fury Road', 2015, 'Action', 'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler.', 'George Miller', 120),
('Joker', 2019, 'Crime', 'In Gotham City, a mentally troubled comedian embarks on a downward spiral of social revolution.', 'Todd Phillips', 122),
('Bohemian Rhapsody', 2018, 'Biography', 'The story of the legendary rock band Queen and lead singer Freddie Mercury.', 'Bryan Singer', 134),
('Black Panther', 2018, 'Action', 'TChalla returns home to take his rightful place as king of Wakanda.', 'Ryan Coogler', 134),
('Harry Potter and the Sorcerers Stone', 2001, 'Fantasy', 'A young boy discovers he is a wizard on his eleventh birthday.', 'Chris Columbus', 152),
('The Hunger Games', 2012, 'Sci-Fi', 'Katniss Everdeen voluntarily takes her sisters place in a deadly televised competition.', 'Gary Ross', 142),
('The Twilight Saga: Breaking Dawn - Part 2', 2012, 'Fantasy', 'After the birth of Renesmee, the Cullens gather other vampire clans.', 'Bill Condon', 115),
('Captain Marvel', 2019, 'Action', 'Carol Danvers becomes one of the universes most powerful heroes.', 'Anna Boden, Ryan Fleck', 123),
('Doctor Strange', 2016, 'Fantasy', 'A surgeon gains mystical powers after a car accident ruins his career.', 'Scott Derrickson', 115),
('Thor: Ragnarok', 2017, 'Action', 'Thor must escape the alien planet Sakaar in time to save Asgard from Hela.', 'Taika Waititi', 130),
('Iron Man', 2008, 'Action', 'After being held captive, Tony Stark builds a suit of armor to fight injustice.', 'Jon Favreau', 126),
('Guardians of the Galaxy', 2014, 'Adventure', 'A group of intergalactic criminals must pull together to stop a fanatical warrior.', 'James Gunn', 121),
('Ant-Man', 2015, 'Action', 'Armed with a suit that allows him to shrink, a thief must aid his mentor in protecting its secret.', 'Peyton Reed', 117),
('Spider-Man: Homecoming', 2017, 'Action', 'Peter Parker balances his life as an ordinary high school student with his superhero alter-ego.', 'Jon Watts', 133),
('The Lion King', 2019, 'Animation', 'After the murder of his father, a young lion prince flees his kingdom.', 'Jon Favreau', 118),
('Cinderella', 2015, 'Fantasy', 'A kind girl attends a ball at the castle with the help of her fairy godmother.', 'Kenneth Branagh', 105),
('Beauty and the Beast', 2017, 'Fantasy', 'A young woman is imprisoned in an enchanted castle by a beast.', 'Bill Condon', 129),
('Aladdin', 2019, 'Adventure', 'A kind-hearted street urchin vies for the love of a beautiful princess.', 'Guy Ritchie', 128),
('Maleficent', 2014, 'Fantasy', 'A vengeful fairy is driven to curse an infant princess.', 'Robert Stromberg', 97),
('The Jungle Book', 2016, 'Adventure', 'A man-cub named Mowgli embarks on a journey of self-discovery.', 'Jon Favreau', 106),
('Alice in Wonderland', 2010, 'Fantasy', 'A young girl falls into a rabbit hole and enters a world of whimsical characters.', 'Tim Burton', 108)
('A Quiet Place', 2018, 'Horror', 'In a post-apocalyptic world, a family is forced to live in silence.', 'John Krasinski', 90),
('Get Out', 2017, 'Horror', 'A young African-American visits his white girlfriends parents for the weekend.', 'Jordan Peele', 104),
('Parasite', 2019, 'Thriller', 'A poor family schemes to become employed by a wealthy family by infiltrating their household.', 'Bong Joon Ho', 132),
('Her', 2013, 'Romance', 'A lonely writer develops an unlikely relationship with an operating system.', 'Spike Jonze', 126),
('The Shape of Water', 2017, 'Fantasy', 'A mute woman forms a relationship with a mysterious aquatic creature.', 'Guillermo del Toro', 123),
('The Irishman', 2019, 'Crime', 'A mob hitman recalls his possible involvement with the slaying of Jimmy Hoffa.', 'Martin Scorsese', 209),
('No Country for Old Men', 2007, 'Thriller', 'A hunter stumbles upon a drug deal gone wrong and a bag of cash.', 'Ethan Coen, Joel Coen', 122),
('The Lobster', 2015, 'Comedy', 'In a dystopian future, single people are transformed into animals if they fail to find a mate.', 'Yorgos Lanthimos', 119),
('Moonlight', 2016, 'Drama', 'A young African-American man grapples with his identity and sexuality while growing up in Miami.', 'Barry Jenkins', 111),
('Lady Bird', 2017, 'Comedy', 'An artistically inclined seventeen-year-old comes of age in Sacramento, California.', 'Greta Gerwig', 94),
('Call Me by Your Name', 2017, 'Romance', 'In 1980s Italy, a romance blossoms between a seventeen-year-old student and an older man.', 'Luca Guadagnino', 132),
('The Farewell', 2019, 'Drama', 'A Chinese family discovers their grandmother has only a short time left to live.', 'Lulu Wang', 100),
('Jojo Rabbit', 2019, 'Comedy', 'A young boy in Nazi Germany discovers his mother is hiding a Jewish girl.', 'Taika Waititi', 108),
('Knives Out', 2019, 'Mystery', 'A detective investigates the death of a patriarch of an eccentric, combative family.', 'Rian Johnson', 130),
('Little Women', 2019, 'Drama', 'Jo March reflects back and forth on her life, telling the beloved story of the March sisters.', 'Greta Gerwig', 135),
('Once Upon a Time in Hollywood', 2019, 'Comedy', 'A faded television actor and his stunt double strive to achieve fame in the film industry.', 'Quentin Tarantino', 161),
('Marriage Story', 2019, 'Drama', 'Noah Baumbachs incisive and compassionate look at a marriage breaking up.', 'Noah Baumbach', 137),
('The Lighthouse', 2019, 'Horror', 'Two lighthouse keepers try to maintain their sanity while living on a remote island.', 'Robert Eggers', 109),
('1917', 2019, 'War', 'Two British soldiers must deliver a message to stop a deadly attack during WWI.', 'Sam Mendes', 119),
('Portrait of a Lady on Fire', 2019, 'Romance', 'On an isolated island in Brittany, a female painter is obliged to paint a wedding portrait.', 'Céline Sciamma', 122),
('Judas and the Black Messiah', 2021, 'Biography', 'Bill ONeal infiltrates the Black Panther Party to gather intelligence on Chairman Fred Hampton.', 'Shaka King', 126),
('Soul', 2020, 'Animation', 'A musician who has lost his passion for music is transported out of his body.', 'Pete Docter, Kemp Powers', 100),
('Tenet', 2020, 'Sci-Fi', 'A secret agent is given a single word as his weapon to prevent the onset of World War III.', 'Christopher Nolan', 150),
('Minari', 2020, 'Drama', 'A Korean-American family moves to an Arkansas farm in search of their own American Dream.', 'Lee Isaac Chung', 115),
('Sound of Metal', 2019, 'Drama', 'A drummer begins to lose his hearing and must come to grips with a future that will be filled with silence.', 'Darius Marder', 120),
('Nomadland', 2020, 'Drama', 'A woman in her sixties embarks on a journey through the American West, living as a modern-day nomad.', 'Chloé Zhao', 108),
('Promising Young Woman', 2020, 'Thriller', 'A young woman haunted by a tragedy in her past takes revenge on predatory men.', 'Emerald Fennell', 113),
('The Trial of the Chicago 7', 2020, 'History', 'The story of 7 people on trial stemming from various charges surrounding the uprising at the 1968 Democratic National Convention.', 'Aaron Sorkin', 130),
('The Father', 2020, 'Drama', 'A man refuses all assistance from his daughter as he ages.', 'Florian Zeller', 97),
('Mank', 2020, 'Biography', '1930s Hollywood is reevaluated through the eyes of scathing social critic and alcoholic screenwriter Herman J. Mankiewicz.', 'David Fincher', 131),
('Dune', 2021, 'Sci-Fi', 'Paul Atreides leads nomadic tribes in a battle to control the desert planet Arrakis.', 'Denis Villeneuve', 155),
('The Power of the Dog', 2021, 'Drama', 'A charismatic rancher inspires fear and awe in those around him.', 'Jane Campion', 126),
('West Side Story', 2021, 'Musical', 'An adaptation of the 1957 musical, exploring forbidden love and rivalry between gangs.', 'Steven Spielberg', 156),
('CODA', 2021, 'Drama', 'As a CODA (Child of Deaf Adults), Ruby is the only hearing person in her deaf family.', 'Sian Heder', 111),
('King Richard', 2021, 'Biography', 'A look at how tennis superstars Venus and Serena Williams became who they are after the coaching from their father Richard Williams.', 'Reinaldo Marcus Green', 144),
('Encanto', 2021, 'Animation', 'A Colombian teenage girl has to face the frustration of being the only member of her family without magical powers.', 'Jared Bush, Byron Howard, Charise Castro Smith', 99),
('The Lost Daughter', 2021, 'Drama', 'A womans beach vacation takes a dark turn when she begins to confront the troubles of her past.', 'Maggie Gyllenhaal', 121),
('Spencer', 2021, 'Biography', 'During her Christmas holidays with the royal family, Diana decides to leave her marriage to Prince Charles.', 'Pablo Larraín', 117),
('Nightmare Alley', 2021, 'Thriller', 'An ambitious carny with a talent for manipulating people hooks up with a female psychiatrist who is even more dangerous than he is.', 'Guillermo del Toro', 150),
('Tick, Tick... Boom!', 2021, 'Musical', 'On the cusp of his 30th birthday, a promising theater composer navigates love, friendship, and the pressures of life.', 'Lin-Manuel Miranda', 120),
('Drive My Car', 2021, 'Drama', 'After his wifes death, Yusuke is offered to direct a production of Uncle Vanya in Hiroshima.', 'Ryusuke Hamaguchi', 179),
('Licorice Pizza', 2021, 'Romance', 'The story of Alana Kane and Gary Valentine growing up, running around, and going through the treacherous navigation of first love.', 'Paul Thomas Anderson', 133);
