INSERT INTO movie_recommendation.genres (genre_name) VALUES
('Action'),
('Adventure'),
('Animation'),
('Biography'),
('Comedy'),
('Crime'),
('Drama'),
('Fantasy'),
('Historical'),
('Horror'),
('Musical'),
('Mystery'),
('Romance'),
('Sci-Fi'),
('Thriller'),
('War'),
('Western'),
('Action-Comedy'),
('Romantic-Comedy'),
('Dark Comedy'),
('Psychological Thriller'),
('Superhero'),
('Fantasy Adventure'),
('Historical Drama'),
('Epic'),
('Crime Thriller'),
('Post-Apocalyptic'),
('Neo-Noir'),
('Family'),
('Coming-of-Age'),
('Slasher'),
('Found Footage'),
('Parody'),
('Documentary');